//
//  XBehaviorEvent.cs
//
//  Author:
//       ${wuxingogo} <52111314ly@gmail.com>
//
//  Copyright (c) 2015 wuxingogo
//
//  You should have received a copy of the GNU Lesser General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System.Collections.Generic;
using Action = System.Action;

namespace wuxingogo.Runtime
{
	[System.Serializable]
	public class XBehaviorEvent
	{
		public bool IsGlobal = false;
		public string name = "Default";
		
		public XBehaviorState nextState = null;
		public Action Finish = null;
		
		public XBehaviorEvent(string name)
		{
			this.name = name;
		}
		
		public void DoState(){
			if(Finish != null)
			Finish();
			
		}
		
		public void CreateState(string stateName){
			nextState = new XBehaviorState(stateName);
		}
	}
}

