//// ------------------------------------------------------------------------------
////  <autogenerated>
////      This code was generated by a tool.
////      Mono Runtime Version: 2.0.50727.1433
//// 
////      Changes to this file may cause incorrect behavior and will be lost if 
////      the code is regenerated.
////  </autogenerated>
//// ------------------------------------------------------------------------------
//
//using UnityEditor;
//using System.Collections;
//using System;
//using UnityEngine;
//
//
//public class JsonExtensionWindow : XBaseWindow
//{
//	
//	[MenuItem( "Wuxingogo/DataPaser/JsonExtensionWindow " )]
//	static void init()
//    {
//    	Init<JsonExtensionWindow>();
//    }
//    
//    public static JSONObject JSON = null;
//    
//    public override void OnXGUI()
//    {
//    	BeginHorizontal();
//		if(CreateSpaceButton("Open")){
//		
//		}
//		if(CreateSpaceButton("Create")){
//			
//		}
//		EndHorizontal();
//		
//		if( null != JSON ){
//			for (int pos = 0; pos < JSON.keys.Count; pos++) {
//				//  TODO loop in JSON.keys.Count
//				CreateLabel(JSON.keys[pos].ToString());
//			}
//			for (int pos = 0; pos < JSON.list.Count; pos++) {
//				//  TODO loop in JSON.keys.Count
//				CreateLabel(JSON.keys[pos].ToString());
//				
//			}
//		}
//    }
//	
//}
//
//
//
//
