// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using UnityEditor;
using System.Collections;
using UnityEngine;
using System;
using System.Reflection;


public class XWebWindow : XBaseWindow
{
	[MenuItem( "Wuxingogo/Wuxingogo XWebWindow #]" )]
    static void init()
    {
		XWebWindow window = Init<XWebWindow>();
    }

	public override void OnInitialization(params object[] args){
	    
		webViewType = GetTypeFromAllAssemblies("WebView");
		//Init web view
		InitWebView();
		//Get docked property getter MethodInfo
//		dockedGetterMethod = typeof(EditorWindow).GetProperty("docked", fullBinding).GetGetMethod(true);
    }

    void InitWebView(){
		webView = ScriptableObject.CreateInstance(webViewType);
		Type type = this.GetType().BaseType;
		object hostView = type.GetField("m_Parent",BindingFlags.NonPublic | BindingFlags.Instance).GetValue(this);
		webViewType.GetMethod("InitWebView").Invoke(webView, new object[] { hostView, 20,150,(int)position.width - 40 ,(int)position.height - 200,false});
		webViewType.GetMethod("set_hideFlags").Invoke(webView, new object[] {13});
		
		loadURLMethod = webViewType.GetMethod("LoadURL");
		loadURLMethod.Invoke(webView, new object[] {urlText});
		webViewType.GetMethod("SetDelegateObject").Invoke(webView, new object[] {this});
		
		doGUIMethod = webViewType.GetMethod("DoGUI");
		focusMethod = webViewType.GetMethod("SetFocus");

		this.wantsMouseMove = true;
    }

	static BindingFlags fullBinding = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static;
	static StringComparison ignoreCase = StringComparison.CurrentCultureIgnoreCase;
	
	object webView; 
	Type webViewType;
	MethodInfo doGUIMethod;
	MethodInfo loadURLMethod;
	MethodInfo focusMethod;
	
	Vector2 resizeStartPos;
	Rect resizeStartWindowSize;
//	MethodInfo dockedGetterMethod;
	
	string urlText = EditorPrefs.GetString("xwebview_store", "unity3d.com/cn/");

    public override void OnXGUI()
    {
    	BeginHorizontal();
		if(CreateSpaceButton("DeFocus"))
			focusMethod.Invoke(webView, new object[] { false });

		DoButton<string>("UnityScript", SetUrl, "http://docs.unity3d.com/ScriptReference/index.html");
		DoButton<string>("Google", SetUrl, "www.gooogle.com");
		DoButton<string>("Github", SetUrl, "github.com/wuxingogo");
		DoButton<string>("Weibo", SetUrl, "weibo.com/52111314ly?source=blog");
		DoButton<string>("Zhihu", SetUrl, "http://www.zhihu.com/");

		EndHorizontal();
		
		CreateLabel("URL");
		urlText = CreateStringField(urlText);
		
		//Focus on web view if return is pressed in URL field
		if(Event.current.isKey && Event.current.keyCode == KeyCode.Return) {
			

			if(urlText != "")
				SetUrl(urlText);
		}

		if(CreateSpaceButton("Setting")){
			XMethodWindow window = Init<XMethodWindow>();
			window.Target = webView;
		}
		
		//Web view
//		if(webView != null)
//			doGUIMethod.Invoke(webView, new object[] {webViewRect});
    }


	public static Type GetTypeFromAllAssemblies(string typeName) {
		Assembly[] assemblies = System.AppDomain.CurrentDomain.GetAssemblies();
		foreach(Assembly assembly in assemblies) {
			Type[] types = assembly.GetTypes();
			foreach(Type type in types) {
				if(type.Name.Equals(typeName, ignoreCase) || type.Name.Contains('+' + typeName)) //+ check for inline classes
					return type;
			}
		}
		return null;
	}

	private void OnWebViewDirty() {
		this.Repaint();
	}

	public void SetUrl(string str){
		loadURLMethod.Invoke(webView, new object[] {urlText});
		focusMethod.Invoke(webView, new object[] { true });
		urlText = str;
		EditorPrefs.SetString("xwebview_store", urlText);
	}

//	void OnDestroy() {
////		Destroy web view
//		webViewType.GetMethod("DestroyWebView", fullBinding).Invoke(webView, null);
//	}
}
